export {assignGingerly} from './assignGingerly.js';
export {assignTentatively} from './assignTentatively.js';
export {EnhancementRegistry, ItemscopeRegistry, EnhancementRegisteredEvent} from './assignGingerly.js';
export {waitForEvent} from './utils/waitForEvent.js';
export {ParserRegistry, globalParserRegistry} from './parserRegistry.js';
export {parseWithAttrs} from './parseWithAttrs.js';
export {buildCSSQuery} from './buildCSSQuery.js';
export {resolveTemplate} from './resolve/resolveTemplate.js';
export {getHost} from './getHost.js';
export {resolveValues, resolveValue} from './resolve/resolveValues.js';
export {getValues, getValue, hasProtocol, parseProtocolRef, isPlainObject} from './resolve/getValues.js';
export {assignFromAsync} from './assignFromAsync.js';
export {assignFrom} from './assignFrom.js';
export {assignFeatures, FeaturesRegistry, captureFeatureInitVals, PropertyBag, suggestFeatureInfo, getFeatureInfoSuggestions} from './assignFeatures.js';
export {installForwarding} from './DX/installForwarding.js';
export {defineWithFeatures} from './defineWithFeatures.js';
export {nudge} from './handlers/nudge.js';
export {arr} from './handlers/arr.js';
export {} from './handlers/manageTemplateList.js';
import './object-extension.js';