export {assignGingerly} from './assignGingerly.js';
export {assignTentatively} from './assignTentatively.js';
export {EnhancementRegistry, ItemscopeRegistry, EnhancementRegisteredEvent} from './assignGingerly.js';
export {waitForEvent} from './waitForEvent.js';
export {ParserRegistry, globalParserRegistry} from './parserRegistry.js';
export {parseWithAttrs} from './parseWithAttrs.js';
export {buildCSSQuery} from './buildCSSQuery.js';
export {resolveTemplate} from './resolveTemplate.js';
export {getHost} from './getHost.js';
export {resolveValues, resolveValue} from './resolveValues.js';
export {assignFromAsync} from './assignFromAsync.js';
export {assignFrom} from './assignFrom.js';
export {assignFeatures, FeaturesRegistry, captureFeatureInitVals, PropertyBag, suggestFeatureInfo, getFeatureInfoSuggestions} from './assignFeatures.js';
export {installForwarding} from './installForwarding.js';
export {defineWithFeatures} from './defineWithFeatures.js';
export {resolveAndAssignFeatures} from './resolveAndAssignFeatures.js';
export {nudge} from './nudge.js';
export {} from './handlers/manageTemplateList.js';
import './object-extension.js';